version: "3"
services:
    mongo:
        image: mongo
        container_name: global-mongo-service
        restart: unless-stopped
        volumes:
            - mongo_data:/data/configdb
            - mongo_data:/data/db
        ports:
            - 27017:27017        
volumes:
    mongo_data: {}